# Generated by Django 2.0 on 2019-05-15 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elaine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='qustion',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='vote',
            new_name='votes',
        ),
    ]
